In [1]:
  #1D array
import numpy as np
array_1d = np.array([1,2,3])
print(f"1 dimensional array = {array_1d}")

#2D array
array_2d = np.array([[1,2,3],[4,5,6]])
print(f"2 dimensional array,\n{array_2d}")
array_2d.shape

1 dimensional array = [1 2 3]
2 dimensional array,
[[1 2 3]
 [4 5 6]]


(2, 3)

In [2]:
#3D array
array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(f"3 dimensional array,\n{array_3d}")

3 dimensional array,
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [3]:
array_3d.shape

(2, 2, 3)

list vs numpy

In [4]:
#list
import time
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("\n List operation time:", time.time()-start)


 List operation time: 0.5311291217803955


In [5]:
#numpy
start = time.time()
np_array = np.arange(10000000)*2
print("\n Numpy operation time:", time.time()-start)


 Numpy operation time: 0.027370691299438477


In [6]:
#list
py_list= [1,2,3]
print("python list multiplication", py_list*3)

python list multiplication [1, 2, 3, 1, 2, 3, 1, 2, 3]


In [7]:
#numpy
np_list = np.array([1,2,3]) #element wise multiplication
print("numpy array multiplication", np_list*3) #here 3 is a scalar, we can perform the vector multiplication

numpy array multiplication [3 6 9]


In [8]:
# Rank 0 (scalar)
a1 = np.array(10)
a1.ndim

0

In [9]:
# Rank 1 (vector)
a2 = np.array([1,2,3])
a2.ndim

1

In [10]:
# Rank 2  (matrix)
a3= np.array([
    [1,2,3],
    [4,5,6]
])
a3.ndim

2

In [11]:
#class work
five_matrix = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])
print("rank = ",five_matrix.ndim)
print("shape = ",five_matrix.shape)
print(five_matrix)

rank =  2
shape =  (5, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [12]:
zeros = np.zeros((5,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
ones = np.ones((5,5), dtype= "int8")
print(ones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [14]:
np.ones(shape=(4,5), dtype= "int8")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [15]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(a.sum(axis=0)) #column wise sum
print(a.sum(axis=1)) # row wise sum

[12 15 18]
[ 6 15 24]


In [16]:
#random
random = np.random.random((3,3))
print(random)

[[0.40508893 0.2657089  0.72160569]
 [0.77943446 0.70414839 0.37557612]
 [0.64256263 0.83827792 0.91041999]]


In [17]:
# full
full = np.full((3,3), 5)
print(full)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [18]:
#linespace() | creates evenly spaced value
arr = np.linspace(0,100,20)
print(arr)

[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]


In [19]:
# diag | creates diagonal matirix
arr = np.diag([1,2,4])
arr

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 4]])

In [20]:
# eye  | Creates matrix with ones on diagonal
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
arrr = np.eye(3,4)
arrr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [22]:
# identity () | creates identity matrix(always square matrix)
arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
# creating random array
arr = np.random.rand(2,3)
arr

array([[0.47736963, 0.91058947, 0.79491593],
       [0.03973404, 0.18347608, 0.85581655]])

In [26]:
#arrange
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [28]:
arr = np.arange(3,9) #start and end
arr

array([3, 4, 5, 6, 7, 8])