In [96]:
import numpy as np

In [97]:
arr = np.array([1,2,3,4,5])
print(arr)
arr.shape

[1 2 3 4 5]


(5,)

In [98]:
arr.ndim

1

In [ ]:
arr = np.array(["apple", "banana", "mangoooos"])
arr.dtype

dtype('<U9')

In [ ]:
#array reshaping
arr = np.array([
    [1,2,2],
    [5,6,7]
])
reshape_2d = arr.reshape(3,2)
reshape_2d

array([[1, 2],
       [2, 5],
       [6, 7]])

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
reshaping = arr.reshape(2,5)
reshaping

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
# flattening
falltened_array = reshaping.flatten()
falltened_array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.array([
    [1,2,2],
    [5,6,7]
])
print(arr.shape)
transpose = arr.T
print(transpose)
print(transpose.shape)

(2, 3)
[[1 5]
 [2 6]
 [2 7]]
(3, 2)


In [ ]:
# NumPy array operations
#indexing and slicing
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[2:5])

[3 4 5]


In [ ]:
# class task 2D slicing | [row_start:row_end, column_start: column_end]
arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])
print(arr[0:2,0:4])

[[1 2 3 4]
 [6 7 8 9]]


In [ ]:
#when only two row needed
arr = np.array([
    [1,2,3],
    [4,5,6],
    [11,12,13]
])
print(arr[0:2])

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr[:2])

[[1 2 3]
 [4 5 6]]


In [ ]:
# need first two column only

# print(arr[: :]) # all

print(arr[:,:2])

[[ 1  2]
 [ 4  5]
 [11 12]]


In [ ]:
# reverse rows
print(arr[::-1])

[[11 12 13]
 [ 4  5  6]
 [ 1  2  3]]


In [ ]:
# column reverse
print(arr[:,::-1])

[[ 3  2  1]
 [ 6  5  4]
 [13 12 11]]


In [ ]:
# sorting
unsorted = np.array([2,3,1,0,8,7,9])
print(np.sort(unsorted))

[0 1 2 3 7 8 9]


In [ ]:
# sorting in 2D
two_d_unsorted = np.array([
    [1, 4, 2],
    [4, 2, 6],
    [0,4,1]
])

print(np.sort(two_d_unsorted))

[[1 2 4]
 [2 4 6]
 [0 1 4]]


In [ ]:
print(np.sort(two_d_unsorted, axis=0)) # row

[[0 2 1]
 [1 4 2]
 [4 4 6]]


In [ ]:
print(np.sort(two_d_unsorted, axis=1)) # column

[[1 2 4]
 [2 4 6]
 [0 1 4]]


In [ ]:
# filter
numbers = np.array([1,2,3,4,5,6,7,8])
even_num = numbers[numbers % 2 == 0]
print(even_num)

[2 4 6 8]


In [ ]:
#filter with mask
mask = numbers > 5
print(numbers[mask])

[6 7 8]


In [ ]:
numbers[numbers>5] = 1000
print(numbers)

[   1    2    3    4    5 1000 1000 1000]


In [ ]:
# np.where
where_result = np.where(numbers % 2 == 0, "even", "odd")
print(where_result)

['odd' 'even' 'odd' 'even' 'odd' 'even' 'even' 'even']


In [ ]:
where_res = np.where(numbers ==5)
print(where_res)

(array([4]),)


In [ ]:
num = np.array([1,2,6,5,34,65])
conditional_array = np.where(num<6, num*2,num)
print(conditional_array)

[ 2  4  6 10 34 65]


In [ ]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
b = np.array([11,2,5])
add_row = np.vstack((a,b))
print(add_row)

[[ 1  2  3]
 [ 4  5  6]
 [11  2  5]]


In [ ]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
b = np.array([
    [11],
    [12]
])
add_column = np.hstack((a,b))
print(add_column)

[[ 1  2  3 11]
 [ 4  5  6 12]]
